---
- hosts: localhost
  tags:
    - classic
  roles:
  - role: standard-test-source

- hosts: localhost
  tags:
    - classic
  tasks:
  - name: Make sure fedpkg and selinux bindings are installed
    shell: dnf -y install --skip-broken fedpkg python3-libselinux libmodulemd-devel
  - name: Copy spec file to remote machine
    copy:
      src: "{{ playbook_dir }}/../libmodulemd.spec"
      dest: /tmp/libmodulemd.spec
  - name: Install build deps
    shell: dnf -y builddep /tmp/libmodulemd.spec

- hosts: localhost
  tags:
    - classic
  roles:
  - role: standard-test-basic
    tests:
    - build:
        dir: .
        run: meson -Dtest_installed_lib=true source
    - unittests:
        dir: .
        run: ninja test
